library(datasets)
plot4 <- function() {
    data_set <- read.table("household_power_consumption.txt",sep = ";",header =TRUE)
    ansy_data <- subset(data_set,as.character(data_set$Date) %in% c("1/2/2007","2/2/2007"))
    ansy_data$Sub_metering_1 <- as.numeric(as.character(ansy_data[,"Sub_metering_1"]))
    ansy_data$Sub_metering_2 <- as.numeric(as.character(ansy_data[,"Sub_metering_2"]))
    ansy_data$Voltage <- as.numeric(as.character(ansy_data[,"Voltage"]))
    ansy_data$Global_reactive_power <- as.numeric(as.character(ansy_data[,"Global_reactive_power"]))
    par(mfrow = c(2,2))
    par(cex.axis = 1 )
    with(ansy_data, {
        plot.ts(Global_active_power,xaxt="n")
        axis(1,at= c(0,1440,2880),labels=c("Thu","Fri","Sat"))
        plot.ts(Voltage,xaxt="n",xlab = "datatime")
        axis(1,at= c(0,1440,2880),labels=c("Thu","Fri","Sat"))
        plot.ts(Sub_metering_1,col="gray",xaxt="n",ylim=c(0,40),xlim=c(0,2880),ylab="Energy Sub Metering",xlab="")
        par(new = TRUE)
        plot.ts(Sub_metering_2,col="red",xaxt="n",ylim=c(0,40),xlim=c(0,2880),ylab="",xlab="")
        par(new = TRUE)
        plot.ts(Sub_metering_3,col="blue",xaxt="n",ylim=c(0,40),xlim=c(0,2880),ylab="",xlab="")
        legend("topright", lty = 1, col = c("gray","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.1)
        axis(1,at= c(0,1440,2880),labels=c("Thu","Fri","Sat"))
        plot.ts(Global_reactive_power,xaxt="n",xlab = "datatime")
        axis(1,at= c(0,1440,2880),labels=c("Thu","Fri","Sat"))
        }
    )
    dev.copy(png,file = "plot4.png",width=480,height=480)
    dev.off()
}